#!/bin/bash
xhost +local:docker
docker run -it --rm     --name robotics_intro     --net=host     -e DISPLAY=$DISPLAY     -v /tmp/.X11-unix:/tmp/.X11-unix     -v $(pwd):/opt/ws/src/code     robotics_intro:latest bash
